on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    container: "node:alpine"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Global packages
        run: npm -g ls --depth=0
      - name: Build back-end and front-end
        run: npm ci --prefix=back-end && npm ci --prefix=front-end
      - name: Run ESLint
        run: npx eslint .